---
# tasks file for shell
- name: Tasks for shell setup
  tags:
    - shell
  vars:
    shell_startship_check: "{{ lookup('env', 'STARSHIP_SHELL') }}"
    shell_zsh_check: "{{ lookup('env', 'ZSH') }}"
    shell_asdf_check: "{{ lookup('env', 'ASDF_DIR') }}"
  block:
    - name: Clone TPM
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: /home/$USER/.tmux/plugins/tpm
    - name: Install Oh-my-zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not shell_zsh_check
    - name: Install starship
      ansible.builtin.shell:
        cmd: sh - "$(curl -sS https://starship.rs/install.sh)
      when: not shell_startship_check
    - name: Clone ZSH Plugins
      ansible.builtin.git:
        repo: https://github.com/{{ item }}
        dest: /home/$USER/.oh-my-zsh/custom/{{ item }}
      with_items:
        - Aloxaf/fzf-tab.git
        - zsh-users/zsh-autosuggestions.git
        - zsh-users/zsh-syntax-highlighting.git
    - name: Clone asdf
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: /home/$USER/.asdf
      when: not shell_asdf_check
    - name: Kubectl Directory
      ansible.builtin.file:
        dest: /home/$USER/.kube
        state: directory
    - name: Link Packages
      ansible.builtin.shell:
        cmd: cd /home/$USER/git/dotfiles/.config; stow -t /home/$USER/.config/{{ item }} {{ item }}
      with_items:
        - nvim
        - zsh
        - tmux
        - bat
    - name: Link zshenv
      ansible.builtin.file:
        mode: '755'
        src: '/home/$USER/git/dotfiles/.zshenv'
        dest: '/home/$USER/.zshenv'
        state: link
