# tasks file for shell
- name: Tasks for shell setup
  tags:
    - shell
  vars:
    shell_startship_check: "{{ lookup('env', 'STARSHIP_SHELL') }}"
    shell_zsh_check: "{{ lookup('env', 'ZSH') }}"
    user: "mvaldes"
  block:
    - name: Clone TPM
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: "/home/{{ user }}/.tmux/plugins/tpm"
    - name: Install Oh-my-zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not shell_zsh_check
    - name: Install starship
      ansible.builtin.shell:
        cmd: sh - "$(curl -sS https://starship.rs/install.sh)
      when: not shell_startship_check
    - name: Clone ZSH Plugins
      ansible.builtin.git:
        repo: https://github.com/{{ item }}
        dest: "/home/{{ user }}/.oh-my-zsh/custom/{{ item }}"
      with_items:
        - Aloxaf/fzf-tab.git
        - zsh-users/zsh-autosuggestions.git
        - zsh-users/zsh-syntax-highlighting.git
    - name: Kubectl Directory
      ansible.builtin.file:
        dest: "/home/{{ user }}/.kube"
        state: directory
    - name: Link Packages
      ansible.builtin.shell:
        cmd: cd /home/{{ user }}/git/dotfiles/.config; stow -t /home/{{ user }}/.config/{{ item }} {{ item }}
      with_items:
        - nvim
        - zsh
        - tmux
        - bat
    - name: Link zshenv
      ansible.builtin.file:
        mode: '755'
        src: "/home/{{ user }}/git/dotfiles/.zshenv"
        dest: "/home/{{ user }}/.zshenv"
        state: link
