dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: molecule-ubuntu
    image: ubuntu:24.04
    pre_build_image: false
    dockerfile: ./Dockerfile
verifier:
  name: ansible
scenario:
  test_sequence:
    - converge
    - verify
