- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check user exists
      ansible.builtin.user:
        name: "mvaldes"
        state: present
    - name: Check Core Packages
      ansible.builtin.package:
        name:
          - neovim
          - tmux
    - name: Check Repos Cloned
      ansible.builtin.stat:
        path: "/home/mvaldes/git/{{ item }}"
      loop:
        - vorpal
        - k8s-apps
        - twitch-bot
