- name: Installs asdf plugins
  tags:
    - asdf
  block:
    - name: 'Installs asdf plugins'
      ansible.builtin.command:
        cmd: asdf plugin add {{ item }}
      with_items:
        - golang
        - helm
        - jq
        - kubectl
        - lua
        - nodejs
        - ruby
        - rust
        - stern
        - terraform
        - terragrunt
        - awscli
        - sops
        - lazygit
        - tflint
