- name: Install applications for i3 system
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - i3
  block:
    - name: Link Packages
      ansible.builtin.shell:
        cmd: cd /home/$USER/git/dotfiles/.config; stow -t /home/$USER/.config/{{ item }} {{ item }}
      with_items:
        - rofi
        - i3
        - polybar
        - dunst
        - picom
    - name: 'Install packages'
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      with_items:
        - '{{ i3 }}'
