user: 'mvaldes'
git_repo_base: '$HOME/git'
git_username: 'mvaldes14'
git_repos:
  - terraform
  - terraform.nvim
  - dotfiles
  - dotfiles-nix
  - ansible_playbooks
  - blog
  - twitch-bot
  - chef
  - pulumi
  - k8s-apps
utilities:
  - xclip
  - tldr
  - progress
  - tree
  - rsync
  - rclone
  - prettyping
  - bat
  - ncdu
  - neovim
  - zsh
  - jq
  - fzf
  - neofetch
  - tmux
  - fd-find
  - ripgrep
  - stow
  - python3-venv
  - python3-pip
  - unzip
  - youtube-dl
  - age
cargo:
  - xcp
  - hyperfine
pip:
  - ansible-lint
  - pre-commit
  - molecule
  - molecule-plugins[docker]
  - pytest-testinfra
npm:
  - vite
  - pnpm
