user: 'mvaldes'
git_repo_base: '$HOME/git'
git_username: 'mvaldes14'
git_repos:
  - wiki
  - dotfiles
  - k8s-apps
  - twitch-bot
  - blog
  - terraform
  - dotfiles-nix
  - ansible_playbooks
  - meal-notifier
  - gh-actions
  - terraform.nvim
  - chef
  - vorpal
  - todoist.nvim
  - linear.nvim
  - aoc
  - timerly
  - server_scraper
  - mvaldes14
  - deckmaster-config
  - pulumi
  - nvim-lint
  - asdf-tea
  - vue-composer
  - ELKTwitterIngestion
  - Twitter-CLI
  - babylog
  - flask-reddithwswap
base_apps:
  - neovim
  - tmux
  - fd-find
  - ripgrep
  - zsh
  - tree
