---
# tasks file for windows
- name: Install windows apps
  community.windows.win_scoop:
    name: "{{ item }}"
    state: present
  loop:
    - firefox
    - obsidian
    - obs-studio
    - spotify
    - discord
    - gimp
    - krita
    - steam
    - flameshot
    - windows-terminal
  tags:
    - windows
