- name: Post Reboot Tasks
  block:
      - name: Reboot the machine
        ansible.builtin.reboot:
          reboot_timeout: 300
          pre_reboot_delay: 30
          test_command: whoami
    - name: Wait for machine
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 600
    - name: Uncordon node
      kubernetes.core.k8s_drain:
        state: uncordon
        name: "{{ inventory_hostname }}"
        kubeconfig: "/home/{{ user }}/.kube/config"
