- name: Vector Directory
  ansible.builtin.file:
    path: /opt/vector
    state: directory
    mode: "0755"
- name: Updates packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 300
    pre_reboot_delay: 30
    test_command: whoami
