# tasks file for homelab
- name: Update
  apt:
    update_cache: yes
- name: Install ssh
  apt:
    name: openssh-server
    state: present
- name: SSH Access Setup
  include_tasks:
    file: access.yml
    apply:
      tags:
        - ssh
  tags:
    - ssh
- name: Before Reboot
  include_tasks:
    file: before.yml
    apply:
      delegate_to: localhost
      tags:
        - before
  tags:
    - before
- name: Prepare Reboot
  include_tasks:
    file: after.yml
    apply:
      tags:
        - after
  tags:
    - after
