# tasks file for homelab
- name: Before Reboot
  block:
    - name: Node dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ node_dependencies }}"
    - name: Python dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop: "{{ python_dependencies }}"
    - name: Vector Directory
      ansible.builtin.file:
        path: /opt/vector
        state: directory
        mode: "0755"
    - name: Updates packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
    - name: Reboot the machine
      ansible.builtin.reboot:
        reboot_timeout: 300
        pre_reboot_delay: 30
- name: Prepare Reboot
  connection: local
  block:
    - name: Cordon node
      kubernetes.core.k8s_drain:
        state: cordon
        name: "{{ inventory_hostname }}"
        kubeconfig: "/home/{{ user }}/.kube/config"
    - name: Drain node
      kubernetes.core.k8s_drain:
        state: drain
        name: "{{ inventory_hostname }}"
        kubeconfig: "/home/{{ user }}/.kube/config"
        delete_options:
          ignore_daemonsets: true
          delete_emptydir_data: true
          force: true
          disable_eviction: true
- name: Post Reboot
  connection: local
  block:
    - name: Wait for machine
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
    - name: Uncordon node
      kubernetes.core.k8s_drain:
        state: uncordon
        name: "{{ inventory_hostname }}"
        kubeconfig: "/home/{{ user }}/.kube/config"
