# tasks file for homelab
- name: Updates packages
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
- name: Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - python3-kubernetes
- name: Vector Directory
  ansible.builtin.file:
    path: /opt/vector
    state: directory
    mode: "0755"
- name: SSH Access Setup
  include_tasks:
    file: access.yml
    apply:
      tags:
        - ssh
  tags:
    - ssh
- name: Kubernetes Drain
  delegate_to: localhost
  connection: local
  vars:
    ansible_python_interpreter: /home/mvaldes/git/ansible_playbooks/.venv/bin/python
  block:
    - name: Cordon node
      kubernetes.core.k8s_drain:
        state: cordon
        name: "{{ inventory_hostname }}"
    - name: Drain node
      kubernetes.core.k8s_drain:
        state: drain
        name: "{{ inventory_hostname }}"
        delete_options:
          ignore_daemonsets: true
          delete_emptydir_data: true
          force: true
          disable_eviction: true
- name: Reboot the machine
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
    pre_reboot_delay: 30
    test_command: whoami
- name: Wait for machine
  ansible.builtin.wait_for_connection:
    delay: 30
    timeout: 600
- name: Kubernetes Uncordon
  delegate_to: localhost
  connection: local
  vars:
    ansible_python_interpreter: /home/mvaldes/git/ansible_playbooks/.venv/bin/python
  block:
    - name: Uncordon node
      kubernetes.core.k8s_drain:
        state: uncordon
        name: "{{ inventory_hostname }}"
