- name: Install applications for Ubuntu
  tags:
    - pkg
  #TODO: Must install nerdfonts here
  #https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
  # setup neovim ppa unstable
  # install neovim, i3, rofi
  block:
    - name: 'Create user'
      ansible.builtin.user:
        name: '{{ user }}'
        state: present
        create_home: true
    - name: 'Install apps'
      become: true
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: true 
      loop: '{{ base_apps }}'
    - name: 'Create base git folder'
      ansible.builtin.file:
        state: directory
        path: '{{ git_repo_base }}'
    - name: 'Clone repos'
      ansible.builtin.git:
        repo: "https://github.com/{{ git_username }}/{{ item }}.git"
        dest: '{{ git_repo_base }}/{{ item }}'
      loop: '{{ git_repos }}'
