- name: Install applications for Ubuntu
  tags:
    - pkg
  block:
    - name: 'Create user'
      ansible.builtin.user:
        name: '{{ user }}'
        state: present
        create_home: true
    - name: 'Update Cache'
      ansible.builtin.apt:
        update_cache: true
    - name: 'Create base git folder'
      ansible.builtin.file:
        state: directory
        path: '{{ git_repo_base }}'
    - name: 'Clone repos'
      ansible.builtin.git:
        repo: "https://github.com/{{ git_username }}/{{ item }}.git"
        dest: "{{ git_repo_base }}/{{ item }}"
      loop: '{{ git_repos }}'
