- name: Install applications for Ubuntu
  tags:
    - pkg
  block:
    - name: 'Neovim PPA'
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present
    - name: 'Install apps'
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      loop: '{{ base_apps }}'
    - name: 'Create base git folder'
      ansible.builtin.file:
        state: directory
        path: '{{ git_repo_base }}'
    - name: 'Clone repos'
      ansible.builtin.git:
        repo: "https://github.com/{{ git_username }}/{{ item }}.git"
        dest: '/home/{{user}}//{{ git_repo_base }}/{{ item }}'
      loop: '{{ git_repos }}'
    - name: Setup Shell
      ansible.builtin.include_role:
        name: shell
