- name: Demo Youtube
  hosts: homelab
  gather_facts: false
  tasks:
    - name: K3s
      ignore_errors: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
      loop:
        - k3s-agent
    - name: Hola
      ansible.builtin.debug:
        msg: "Complete!"
